# Generated by Django 3.1 on 2020-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='DatePurchase',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='LastService',
            field=models.DateField(),
        ),
    ]
